apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: jklee-test
  namespace: ''                         # kubeflow api 버전과 Experiment, Namespace 정의
spec:    # 실험에 대한 다양한 옵션 정의
  maxTrialCount: 24
  parallelTrialCount: 3
  maxFailedTrialCount: 3
  resumePolicy: Never
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: val-acc
    additionalMetricNames:
      - val-loss                        # 무조건 형식 이렇게
  algorithm:
    algorithmName: random
    algorithmSettings: []
  parameters:
    - name: learning_rate
      parameterType: double
      feasibleSpace:
        min: '0.01'
        max: '0.1'
        step: '0.01'
    - name: dropout
      parameterType: double
      feasibleSpace:
        min: '0.1'
        max: '0.3'
    - name: opt
      parameterType: int
      feasibleSpace:
        min: '0'
        max: '1'
  metricsCollectorSpec:
    source:
      fileSystemPath:
        path: /var/log/katib/metrics.log
        kind: File
  trialTemplate:    # Trial의 template 정의
    primaryContainerName: training-container
    successCondition: status.conditions.#(type=="Complete")#|#(status=="True")#
    failureCondition: status.conditions.#(type=="Failed")#|#(status=="True")#
    retain: True      # log 확인 가능
    trialParameters:
      - name: learning_rate
        description: Learning Rate for modeling training
        reference: learning_rate
      - name: dropout
        description: dropout rate
        reference: dropout
      - name: opt
        description: Optimizer for modeling training
        reference: opt
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
              - name: training-container
                image: docker.io/nevret/nevret-katib-mnist:0.2-gpu
                resources:
                  limits:
                    nvidia.com/mig-1g.10gb: 0      # GPU, 제대로 써주거나 아니면 resources:를 제외하거나
                command:
                  # - "CUDA_VISIBLE_DEVICES="
                  - "python"
                  - "/mnist-katib-random.py"
                  - "--learning_rate=${trialParameters.learning_rate}"
                  - "--dropout=${trialParameters.dropout}"
                  - "--opt=${trialParameters.opt}"
            restartPolicy: Never